### ISSUE TITLE
Firebird Emu crashes on startup since emulating a correct flash img for the first time

### ISSUE THREAD

**Issue by D33VIL** [nspire-emus/firebird#186]
First to mention some basic information; The crash occured on arch linux using the latest version of Firebird, using a boot1, boot2, diags and manuf image created with the latest version of Ndless and PolyDumper and a TI Nspire CX OS image of version 4.5.0.1180.

So I created a flash image based on the stuff I mentioned before and when emulating for the first time, Firebird kinda froze and crashed after a few seconds. Since then it instantly crashes on startup. 

#157

**Comment by Vogtinator** [comment]
Please provide a stack trace. I assume the saved state is somehow corrupted, so resuming on startup causes Firebird to crash.

**Comment by D33VIL** [comment]
```bash
> nspire_emu

qrc:/qml/qml/Keypad.qml:264:9: QML NAlphaButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/qml/Keypad.qml:53:9: QML NBigButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/qml/Keypad.qml:60:9: QML NBigButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/qml/Keypad.qml:67:9: QML NBigButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/qml/Keypad.qml:21:9: QML NBigButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/qml/Keypad.qml:28:9: QML NBigButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/qml/qml/Keypad.qml:35:9: QML NBigButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[1]    72502 segmentation fault (core dumped)  nspire_emu
```

Output from gdb

```bash
#1  0x00007ffff4e6f240 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff4e6f311 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff63c7020 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()>
No symbol table info available.
#4  0x00007ffff636d4cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQ>
No symbol table info available.
#5  0x00007ffff6191e52 in QThread::exec() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff6af1f89 in ?? () from /usr/lib/libQt5Qml.so.5
No symbol table info available.
#7  0x00007ffff6192fc6 in ?? () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#8  0x00007ffff602a46f in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#9  0x00007ffff5bf93d3 in clone () from /usr/lib/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7ffff0adb700 (LWP 73081)):
#0  0x00007ffff5beeabf in poll () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff4e6f240 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff4e6f311 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff63c7020 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()>
No symbol table info available.
#4  0x00007ffff636d4cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQ>
No symbol table info available.
#5  0x00007ffff6191e52 in QThread::exec() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff2648b28 in ?? () from /usr/lib/libQt5DBus.so.5
No symbol table info available.
#7  0x00007ffff6192fc6 in ?? () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#8  0x00007ffff602a46f in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#9  0x00007ffff5bf93d3 in clone () from /usr/lib/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7ffff1ab9700 (LWP 73080)):
#0  0x00007ffff5beeabf in poll () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff2c9e630 in ?? () from /usr/lib/libxcb.so.1
No symbol table info available.
#2  0x00007ffff2ca02db in xcb_wait_for_event () from /usr/lib/libxcb.so.1
No symbol table info available.
#3  0x00007ffff277bb81 in ?? () from /usr/lib/libQt5XcbQpa.so.5
No symbol table info available.
#4  0x00007ffff6192fc6 in ?? () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff602a46f in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#6  0x00007ffff5bf93d3 in clone () from /usr/lib/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff2c7de40 (LWP 73076)):
#0  0x00005555555929a2 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by Vogtinator** [comment]
The thread backtraces are unfortunately not helpful at all - can you try again with debug symbols?

**Comment by D33VIL** [comment]
I am a little confused rn because I just built the binary from source and not from the arch package and now there seems to be nothing wrong everything works fine.
